fullstack/urls.py
from django.contrib import admin
from django.urls import path, include
from microblog import views

urlpatterns = [
    path('', include('microblog.urls')),
    #path('', views.home, name="home"),
    #path('category/create', views.create_category, name="create_category"),
    #path('category/list', views.category_list, name="category_list"),
    path('admin/', admin.site.urls),
]

microblog/urls.py
#imports
from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'microblog'

#configuracion
urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.CustomSignUpView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('my_posts/', views.MyPostsView.as_view(), name='my_posts'),
    path('edit_post/<int:pk>/', views.EditPostView.as_view(), name='edit_post'),
    path('delete_post/<int:pk>/', views.DeletePostView.as_view(), name='delete_post'),
]

microblog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

#TODO: Crear clase de users
class CustomUsers(AbstractUser):
    personal_url = models.TextField()

#TODO: Crear clase de posts
class Posts(models.Model):
    content = models.CharField(max_length=140, blank=False)
    user = models.ForeignKey(CustomUsers, on_delete=models.CASCADE)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

#TODO: Crear clase de likes
class Likes(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUsers, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

#TODO: Crear clase de comments
class Comments(models.Model):
    content = models.CharField(max_length=140, blank=False)
    user = models.ForeignKey(CustomUsers, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

microblog/forms.py
from django import forms
from .models import Categories, CustomUsers, Posts
from django.contrib.auth.forms import UserCreationForm

class CustomUsersCreationForm(UserCreationForm):
    class Meta:
        model = CustomUsers
        fields = ('username', 'email', 'first_name',
                  'last_name', 'personal_url')

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['content', 'category']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Estas dos lineas son para para cargar contenido con listas desplegables
        self.fields['category'].queryset = Categories.objects.all()
        self.fields['category'].empty_label = "Seleccione una categoría"

microblog/views.py
from django.shortcuts import render, redirect
from .forms import CategoryForm, CustomUsersCreationForm, PostForm
from .models import Posts
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def home(request):
    posts = Posts.objects.select_related('user').all().order_by('-created_at')
    return render(request, 'home.html', { 'posts': posts })

def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('category_list')
    else:
        form = CategoryForm()
    return render(request, 'create_category.html', {'form': form})

def category_list(request):
    return render(request, 'category_list.html')

class CustomSignUpView(CreateView):
    form_class = CustomUsersCreationForm
    template_name = 'register.html'
    success_url = '/login'

class CreatePostView(LoginRequiredMixin, CreateView):
    model = Posts
    form_class = PostForm
    template_name = 'create_post.html'
    success_url = reverse_lazy('microblog:home')

    # Esto es para asignar el usuario autenticado
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class EditPostView(LoginRequiredMixin, UpdateView):
    model = Posts
    form_class = PostForm
    template_name = 'edit_post.html'
    success_url = reverse_lazy('microblog:my_posts')
    # Esto es para validar que el post a editar corresponde al usuario autenticado
    def get_queryset(self):
        return Posts.objects.filter(user = self.request.user)

class DeletePostView(LoginRequiredMixin, DeleteView):
    model = Posts
    template_name = 'delete_post.html'
    success_url = reverse_lazy('microblog:my_posts')

    # Esto es para validar que el post a eliminar corresponde al usuario autenticado
    def get_queryset(self):
        return Posts.objects.filter(user = self.request.user)
    
class MyPostsView(LoginRequiredMixin, ListView):
    model = Posts
    template_name = 'my_posts.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        return Posts.objects.filter(user = self.request.user).select_related('user', 'category').order_by('-created_at')

microblog/templates/category_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de categorias</title>
</head>
<body>
    
</body>
</html>

microblog/templates/create_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear categoria</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</body>
</html>

microblog/templates/delete_post.html
{% extends "template_base.html" %}

{% block title %}
Editar publicación
{% endblock title %}

{% block content %}
<form method="post" action="{% url 'microblog:delete_post' object.id %}">
    {% csrf_token %}
    <p>¿Estás seguro de que deseas eliminar esta publicación?</p>
    <p>{{ object.content }}</p>
    <a href="{% url 'microblog:my_posts' %}">No, volver a mis publicaciones</a>
    <button type="submit">Sí, eliminar, deja de preguntarme</button>
</form>
{% endblock content %}

microblog/templates/edit_post.html
{% extends "template_base.html" %}

{% block title %}
Editar publicación
{% endblock title %}

{% block content %}
<form method="post" action="{% url 'microblog:edit_post' object.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Modificar</button>
</form>
{% endblock content %}

microblog/templates/home.html
{% extends "template_base.html" %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    Estas son las ultimas publicaciones
    <ul>
    {% for post in posts %}
    <li>{{ post.content }} ({{ post.user.name }})</li>
    {% endfor %}
    </ul>
{% endblock content %}

microblog/templates/my_posts.html
{% extends "template_base.html" %}

{% block title %}
    My Posts
{% endblock title %}

{% block content %}
    <h2>My Posts</h2>
    <ul>
        {% for post in posts %}
            <li>{{ post.content }} - {{ post.created_at }} (<a href="{% url 'microblog:edit_post' post.id %}">Edit</a> | <a href="{% url 'microblog:delete_post' post.id %}">Delete</a>)</li>
        {% empty %}
            <li>No posts found.</li>
        {% endfor %}
    </ul>

{% endblock content %}

microblog/templates/register.html
{% extends "template_base.html" %}

{% block title %}
Registro de usuario
{% endblock title %}

{% block content %}
<form method="post" action="{% url 'microblog:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrarse</button>
</form>
{% endblock content %}

microblog/templates/template_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NoviceNerds Microblog | {% block title %}Home{% endblock %}</title>
</head>
<body>
    {% if user.is_authenticated %}
        <p> 👋 {{ user.username }}</p>
        <form method="post" action="{% url 'microblog:logout' %}">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>